### ISSUE TITLE
Your Methods have no Body 77 Errors

### ISSUE THREAD

**Issue by NaderStar** [MrRoundRobin/telegram.bot#25]

**Comment by MrRoundRobin** [comment]
Which VS Version?

I think it's because i used [C# 6](https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6) features like [Expression bodies](https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#expression-bodies-on-method-like-members)

**Comment by fizmhd** [comment]
Hi, 
I am using visual studio 2013
i have 141 Errors
attached screen shots.. 

![capture](https://cloud.githubusercontent.com/assets/568271/9413875/57973bd6-4852-11e5-9e4e-618740d2401f.JPG)

**Comment by MrRoundRobin** [comment]
Can you try VS 2015?

**Comment by spoofi** [comment]
I just tried to compile the project in visual studio 2015 => Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped.

@fizmhd I think, you just need use Visual Studio 2015, because project contains C# 6 features :)

**Comment by sohrablou** [comment]
Hi,
Excuse me Mr Round Robin.
I am Persian language and Iranian them. Please let me help her in Farsi.

سلام. دوست عزیز شما برای استفاده از این ای.پی.آی , باید از ویژوال استادیو 2015 به همراه دات نت فریم ورک 4.5 استفاده کنید.
بهترین راه حل برای استفاده از این ای.پی.آی استفاده از دستور زیر در کامندر خود ویژوال استادیو هستش.
چون نیازمندیهاش رو خودش نصب میکنه و در صورتی که آپدیت بشه راحت میتونی با جابجایی یه فایل دی.ال.ال سریعتر کارت رو پیش ببری.

Install as NuGet package:
```
Install-Package Telegram.Bot

installation link:
https://www.nuget.org/packages/Telegram.Bot/
```

**Comment by marjanjavid** [comment]
Hi,
Its about 10 hours that my bots are not working.I have been installed telegram.bot.dll and other categories from Mr.Round Robin Nugets post and use webhook method to receive and answer for my bots.
but unfortunately unexpectedly all my bots were stopped several hours ago.I checked my the SSL ,It was ok.I dont realy undrestand the problem

**Comment by MrRoundRobin** [comment]
so, do you have any errors, exceptions or other logs? can you confirm that your webhook receives any requests from telegram?

has this anything to do with this issue?

**Comment by Gorniv** [comment]
from https://telegram.me/pwrtelegram
```
Hello.
Please reset the webhooks of all of your bots, because they were all reset by the telegram bot API.
This request applies both to bots that use the official bot API and bots that use the PWRTelegram bot API. You do not need to reset the webhook if you are using long polling (getUpdates).
The webhooks were probably reset because Telegram's making some server side changes or simply messed up the webhook database.

Share this message around to all of your groups and channels, please.
```

**Comment by marjanjavid** [comment]
hello MrRoundRobin 
I dont receive any webhook request on my server from telegram so I dont get any errors.
I have reset one of my bots token ,actually i delete my bot and again create a bot with the same username , but still it doesnt work.
Mr Gorniv did you test it ?i thenk it doesnt work

**Comment by MrRoundRobin** [comment]
so if you have set the webhook correctly and don't get updates that is a problem is not related to the library. maybe check [this faq](https://core.telegram.org/bots/faq#i-39m-having-problems-with-webhooks) and ping BotSupport

**Comment by marjanjavid** [comment]
Thanks for your reply
I had ping BotSupport and after several hours they replied me :
"Hi, we had an issue last night that caused this problems If you call again setWebhook, it should be solved."
I revoke my tokens and set them again and the problem solved easily.It seems it was not necessary to revoke but i have done that before getting BotSupport help.

**Comment by lokeshpanwar777** [comment]
Hi, I try many times but unable to ping the bot to my code part, but earlier it was working fine now its not working.

**Comment by sycobra** [comment]
Anyone can help with this? Everything in the code is correct but still not getting a response from the bot? I check the windows firewall and Telegram.dll and bot.dll and every solution but still not working?

using System;
using Telegram.Bot;
using Telegram.Bot.Types.Enums;
 
       namespace HelloBot
    {
        class Program
        {

        static string token= "******";
      
            static TelegramBotClient Bot = new TelegramBotClient(token);

        static void Main(string[] args)
        {
            Bot.StartReceiving();
            Bot.OnMessage += botmessage;
           
            Console.ReadLine();
        }
            

        private static async void botmessage(object sender, Telegram.Bot.Args.MessageEventArgs e)
        {
            

            if (e.Message.Type == MessageType.Text)
            {
                await Bot.SendTextMessageAsync(e.Message.Chat.Id, "Hello "+e.Message.Chat.Username);

                Console.WriteLine(e.Message.ToString());
             
            }
        }

        }
   }
